name: Backup Supabase Database

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时执行一次

jobs:
  backup:
    runs-on: ubuntu-latest
    timeout-minutes: 330  # 改为330分钟（5.5小时）

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run database backup
        run: python database/backup_supabase.py

      - name: Upload backup as artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup-${{ github.run_number }}
          path: database/backup/
          retention-days: 30

      - name: Commit and push backup log
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add database/backup/
          git diff --staged --quiet || git commit -m "Add backup from run ${{ github.run_number }}"
          git push