name: Scrape Wellington Properties

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *" # Check status every 30 minutes

concurrency:
  group: scrape-property-wellington
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 330

    env:
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      PROPERTY_VALUE_BASE_URL: ${{ secrets.PROPERTY_VALUE_BASE_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Force reset expired status
        run: python database/force_reset_expired_status.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run scraper
        run: python property_wellington.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wellington-property-logs-${{ github.run_number }}
          path: |
            *.log
          retention-days: 7