name: Scrape RealEstate Rent

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *" # Check status every 30 minutes

concurrency:
  group: scrape-realestate-rent
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 330

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      REALESTATE_URL: https://www.realestate.co.nz/residential/sale
      REALESTATE_RENT_URL: https://www.realestate.co.nz/residential/rental
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Force reset expired status
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python database/force_reset_expired_status.py real_estate_rent

      - name: Run scraper
        run: python real_estate_rent.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rent-logs-${{ github.run_number }}
          path: |
            *.log
          retention-days: 7