name: Scrape RealEstate Auckland

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # Run every 6 hours to allow completion

concurrency:
  group: scrape-realestate-auckland
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 330

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      REALESTATE_URL: https://www.realestate.co.nz/residential/sale
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Check if scraping is already running
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python -c "
          import os
          from supabase import create_client, Client
          
          url = os.environ.get('SUPABASE_URL')
          key = os.environ.get('SUPABASE_KEY')
          supabase: Client = create_client(url, key)
          
          result = supabase.table('scraping_progress').select('id').eq('id', 2).eq('status', 'running').execute()
          if result.data:
              print('Auckland scraping is already running. Exiting...')
              exit(1)
          print('No running Auckland scraping found. Proceeding...')
          "

      - name: Force reset expired status
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python database/force_reset_expired_status.py real_estate_auckland

      - name: Run scraper
        run: python real_estate_auckland.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: auckland-logs-${{ github.run_number }}
          path: |
            *.log
          retention-days: 7