name: Scrape RealEstate Rent

on:
  workflow_dispatch:
  schedule:
    # 每30分钟运行一次
    - cron: "*/30 * * * *"

# 添加并发控制，确保同一时间只有一个工作流实例在运行
concurrency:
  group: scrape-realestate-rent
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      REALESTATE_RENT_URL: https://www.realestate.co.nz/residential/rental

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          # 移除 requirements.txt 中对 greenlet>=3.1.0 的显式声明
          pip install -r requirements.txt
          playwright install

      - name: Run scraper
        run: python real_estate_rent.py
