name: Scrape RealEstate Auckland

on:
  workflow_dispatch:
  schedule:
    # 每6小时运行一次，确保有足够的时间间隔
    - cron: "0 */6 * * *"

# 添加并发控制，确保同一时间只有一个工作流实例在运行
concurrency:
  group: scrape-realestate-auckland-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      REALESTATE_URL: https://www.realestate.co.nz/residential/sale

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          # 移除 requirements.txt 中对 greenlet>=3.1.0 的显式声明
          pip install -r requirements.txt
          playwright install

      - name: Run scraper
        run: python real_estate_auckland.py
