name: Scrape RealEstate Rent

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *" # Check status every 30 minutes

concurrency:
  group: scrape-realestate-rent-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      REALESTATE_URL: https://www.realestate.co.nz/residential/sale
      REALESTATE_RENT_URL: https://www.realestate.co.nz/residential/rental
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          # 移除 requirements.txt 中对 greenlet>=3.1.0 的显式声明
          pip install -r requirements.txt
          playwright install

      - name: Run scraper
        run: python real_estate_rent.py
