name: Update Property Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # Run every 6 hours to allow completion

concurrency:
  group: update-property-images
  cancel-in-progress: false

jobs:
  update-images:
    runs-on: ubuntu-latest
    timeout-minutes: 330

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Force reset expired status and check running status
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python -c "
          import os
          from datetime import datetime, timezone, timedelta
          from supabase import create_client, Client
          
          url = os.environ.get('SUPABASE_URL')
          key = os.environ.get('SUPABASE_KEY')
          supabase: Client = create_client(url, key)
          
          # Check current status
          result = supabase.table('scraping_progress').select('*').eq('id', 1).execute()
          if not result.data:
              print('No scraping progress record found')
              exit(1)
          
          record = result.data[0]
          status = record.get('status')
          updated_at = record.get('updated_at')
          
          print(f'Current status: {status}')
          print(f'Last updated: {updated_at}')
          
          # If status is running, check if it's expired (more than 6 hours old)
          if status == 'running' and updated_at:
              from dateutil import parser
              last_update = parser.parse(updated_at)
              now = datetime.now(timezone.utc)
              time_diff = now - last_update
              
              if time_diff > timedelta(hours=6):
                  print(f'Status has been running for {time_diff}, resetting to idle')
                  supabase.table('scraping_progress').update({
                      'status': 'idle',
                      'updated_at': 'now()'
                  }).eq('id', 1).execute()
                  print('Expired status reset to idle')
              else:
                  print(f'Property image update is currently running (started {time_diff} ago). Exiting...')
                  exit(1)
          
          print('Ready to start update')
          "

      - name: Set status to running
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python -c "
          import os
          from supabase import create_client, Client
          
          url = os.environ.get('SUPABASE_URL')
          key = os.environ.get('SUPABASE_KEY')
          supabase: Client = create_client(url, key)
          
          supabase.table('scraping_progress').update({
              'status': 'running',
              'updated_at': 'now()'
          }).eq('id', 1).execute()
          print('Status set to running')
          "

      - name: Run image updater
        run: python property_image.py update_images

      - name: Reset status to idle on completion or failure
        if: always()
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python -c "
          import os
          from supabase import create_client, Client
          
          url = os.environ.get('SUPABASE_URL')
          key = os.environ.get('SUPABASE_KEY')
          supabase: Client = create_client(url, key)
          
          try:
              supabase.table('scraping_progress').update({
                  'status': 'idle',
                  'updated_at': 'now()'
              }).eq('id', 1).execute()
              print('Status reset to idle successfully')
          except Exception as e:
              print(f'Failed to reset status: {e}')
          "

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: image-updater-logs-${{ github.run_number }}
          path: |
            *.log
          retention-days: 7