name: Update Property Images

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *" # Check status every 30 minutes

concurrency:
  group: update-property-images
  cancel-in-progress: true

jobs:
  update-images:
    runs-on: ubuntu-latest
    timeout-minutes: 330

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Force reset expired status
        run: python database/force_reset_expired_status.py

      - name: Run image updater
        run: python property_image.py update_images

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: image-updater-logs-${{ github.run_number }}
          path: |
            *.log
          retention-days: 7