name: Update Property Images

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *" # Check status every 30 minutes

concurrency:
  group: update-property-images
  cancel-in-progress: true

jobs:
  update-images:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Run image updater
        run: python property_image.py update_images